### ISSUE TITLE
最开始打开时页面位置问题

### ISSUE THREAD

**Issue by maxdylan** [GeekaholicLin/hexo-theme-ylion#10]
我新建了两篇博客，hexo s 之后在本地预览，打开发现右侧滚动条自动滚动到最下面，然而不是必现的，偶尔会出现，放到github上之后也存在同样的问题，目测是个bug吧？

**Comment by GeekaholicLin** [comment]
还麻烦你提供一下博客地址~会不会是你的url的hash是#comments，然后导致跳转到了底部？

**Comment by maxdylan** [comment]
博客地址是 maxdylan.github.io

**Comment by GeekaholicLin** [comment]
还是无法复现😂，我已经点了好多次还是不会滚到下面。。

**Comment by maxdylan** [comment]
我也是偶尔会发现那么一两次，不常见，不过你的主题弄得挺漂亮的，给个赞
