### ISSUE TITLE
請問熱門文章為何一直都是只有轉圈圈的圖？

### ISSUE THREAD

**Issue by changchichung** [GeekaholicLin/hexo-theme-ylion#11]
一直都只有在轉圈圈，不會顯示文章標題耶？

**Comment by GeekaholicLin** [comment]
很可能是你的leancloud配置不正确，请详细查看配置文件中的说明，以及[我的博文](http://blog.geekaholic.cn/2017/03/06/%E5%88%B6%E4%BD%9CHexo%E4%B8%BB%E9%A2%98%E8%AF%A6%E7%BB%86%E6%95%99%E7%A8%8B%EF%BC%882%EF%BC%89/)中的相关设置

**Comment by changchichung** [comment]
請問有替代方案嗎？ leancloud 註冊要中國手機號，我沒有..

**Comment by GeekaholicLin** [comment]
@changchichung  你选择使用Github注册还是不可以吗？

**Comment by changchichung** [comment]
是的，還是需要手機號..

**Comment by GeekaholicLin** [comment]
这就有点尴尬了。。试试选择美国节点看看，如果还是不行的话，你可以暂时把这个功能关闭。

**Comment by changchichung** [comment]
OK，我在_config.yml的widget把這個popular拿掉了，側邊沒有出現了，但是每篇文章下面還是會有個類似溫度計的圖示，旁邊一樣在轉圈，請問這個怎麼拿掉？

如圖中紅框所示 http://i.imgur.com/97ZhNV8.png

**Comment by GeekaholicLin** [comment]
@changchichung 我问了相关的人员，解决办法如下：

> 台湾号码应该是可以注册的，在号码前加上 +886 即可。

你可以试试~
