### ISSUE TITLE
按鍵盤快速鍵回上一頁，會導致頁面顯示不正確

### ISSUE THREAD

**Issue by changchichung** [GeekaholicLin/hexo-theme-ylion#14]
如影片所示

第一次我用鍵盤的倒退鍵 backspace 回上一頁，頁面會變成灰色，似乎被蓋上一層layer
但是第二次我用瀏覽器的回上頁按鍵，就不會有這樣的問題

[2017-07-28_09-53-152.zip](https://github.com/GeekaholicLin/hexo-theme-ylion/files/1181790/2017-07-28_09-53-152.zip)

**Comment by GeekaholicLin** [comment]
目前无法判断是你的网站问题还是兼容问题。

已经测试Chrome V59.0.3071.115(64-bit)，你的站点和[我的线上站点](http://blog.geekaholic.cn/)都正常。

测试Firefox V54.0.1 (64-bit)，你的站点不正常，我的线上站点依然正常。所以你可以用你的环境去我的网站试试效果。期待你的进一步反馈。

或者你可以到主题项目目录下的`app.js`文件中 [删掉这行代码](https://github.com/GeekaholicLin/hexo-theme-ylion/blob/master/source/js/app.js#L351)

**Comment by changchichung** [comment]
我發現我用我的Firefox 去看你的網站http://blog.geekaholic.cn/ 也會有一樣的問題，但是Chrome 不會，所以看來是FireFox 的問題了...
