### ISSUE TITLE
关于Disqus不显示问题

### ISSUE THREAD

**Issue by GeekaholicLin** [GeekaholicLin/hexo-theme-ylion#18]
@changchichung 我这边正常，如果你的依然不可以，可以先在开启并部署到Github Pages，我看看能不能找出是什么问题。

**Comment by changchichung** [comment]
https://github.com/changchichung/hexo

這樣子看得到嗎？

**Comment by GeekaholicLin** [comment]
好像配置没什么问题啊。会不会是你的disqus后台设置错了？比如shortname的设置，还有跨域名的设置等等。我不是很熟悉disqus后台，所以你对着官方给出的[问题列表](https://help.disqus.com/customer/portal/articles/472007-i-m-receiving-the-message-%22we-were-unable-to-load-disqus-%22)看看是否有你出现的问题。

**Comment by changchichung** [comment]
剛剛索性把 vps給重啟了，hexo 也來個clean 再重作一次，就沒問題了...
