### ISSUE TITLE
請問該如何修改程式碼部份的顯示？

### ISSUE THREAD

**Issue by changchichung** [GeekaholicLin/hexo-theme-ylion#19]
因為我的網站上會有很多程式碼
但是現在的樣式，沒有刻意強調程式碼的部份，所以突顯不出來
像這樣
![2017-08-15_11-28-33](https://user-images.githubusercontent.com/20943335/29301175-ec31de32-81ac-11e7-8b0c-67de5b6880fc.png)

請問我如果要修改這部份，應該要改哪邊？

**Comment by GeekaholicLin** [comment]
不知道你是如何在markdown中使用代码块的。

目前主题是支持下面的格式的。

<pre>
``` javascript
  function doSomething(){}
```
</pre>
``` javascript
  function doSomething(){}
```
也就是上下各三个反单引号（键盘Tab上方），接着是空格+语言，主体部分写在里面。

**Comment by GeekaholicLin** [comment]
当然Hexo的tag插件也是支持的。

> https://hexo.io/zh-cn/docs/tag-plugins.html#代码块

**Comment by changchichung** [comment]
我是直接用四格空格，如果用你說的三個 ` 會變成這樣
![2017-08-15_11-46-51](https://user-images.githubusercontent.com/20943335/29301542-764b1faa-81af-11e7-9792-fe53798806f9.png)
還是沒有特殊格式，我想說至少有個方塊區域標示出來就好..

**Comment by GeekaholicLin** [comment]
如果方便，请提供你的markdown文件~

我印象中之前测试过，目前ylion主题应该是尚未支持4个空格的。因为渲染出来的html与三个反引号有所不同。

如果是``` 这种仍然没有显示，那可能是你的使用问题？

代码块在本主题的具体体现效果可以点击：

> http://blog.geekaholic.cn/2017/08/10/%E5%8F%8C%E8%AF%AD%E5%AF%B9%E7%85%A7%E7%BF%BB%E8%AF%91%E6%B5%8B%E8%AF%95%E6%96%87%E4%BB%B6.ts/#代码块

这个是该博文对应的markdown源文件：

https://raw.githubusercontent.com/GeekaholicLin/geekaholiclin.github.io/blog-source/source/_posts/%E5%8F%8C%E8%AF%AD%E5%AF%B9%E7%85%A7%E7%BF%BB%E8%AF%91%E6%B5%8B%E8%AF%95%E6%96%87%E4%BB%B6.ts.md

基本上这个文件中的markdown用法都支持，因为这也是Hexo官方提供的基本用法，提交的主题都是要支持的。

**Comment by changchichung** [comment]
[MD 文件 ](https://mega.nz/#!ssgwhYzQ!4w-LCWbCqA8GpFPbWGDLF1m9Wys_Y1qB9HQ4v8o4lyw)

**Comment by changchichung** [comment]
看來是我改到亂了套..
我起一台新的VPS ，重裝Hexo + Theme ，就是正常的樣式
我來主站台測試看看好了，謝謝！
![2017-08-15_14-15-52](https://user-images.githubusercontent.com/20943335/29304169-49b1af30-81c4-11e7-8998-a3b0b0c3b41d.png)

**Comment by GeekaholicLin** [comment]
![image](https://user-images.githubusercontent.com/13808849/29304118-ec3ccc90-81c3-11e7-95bc-69e5d266f4b6.png)

正常显示~

你使用三个反引号，清除构建目录后再构建试试，只要有上面的terminal样式的出现就说明成功。4个空格的暂时不支持哈。我的语言是用了`yaml`，只是为了有点颜色而已。

**Comment by GeekaholicLin** [comment]
噗。同时？
其实没有必要自己起一个服务器啊，这样的话Github Pages不就没有意义了吗？

**Comment by GeekaholicLin** [comment]
没有问题的话那我关闭了~
