### ISSUE TITLE
can not achieve search function

### ISSUE THREAD

**Issue by EthanLXGu** [GeekaholicLin/hexo-theme-ylion#2]
Hi, I am here again, I have tried many methods, but the search function is still cannot be finished.
<img width="592" alt="6211363e-6f24-4376-8a2a-31c710f9108b" src="https://cloud.githubusercontent.com/assets/22212582/23820498/a9901176-0654-11e7-9a3b-36278291fd1c.png">
<img width="585" alt="d6cad136-32b4-4973-ae73-5f872d4b6158" src="https://cloud.githubusercontent.com/assets/22212582/23820504/bf2a5794-0654-11e7-9aeb-1b9e6e4cd853.png">
I always get this issue.

And I have installed search plugin, and search.xml has been generated.
<img width="129" alt="6ff00c82-be78-44c1-a793-0f68625399ff" 
src="https://cloud.githubusercontent.com/assets/22212582/23820519/31c37e7a-0655-11e7-91fb-136782bce959.png">

When you have time, can you help me? Thx!!!!!

**Comment by GeekaholicLin** [comment]
`AV` is not the function of search but the function of a third-party service named `leancloud`.You can trun off this feature in your theme config with `leancloud enable:false`

If you want to use this feature,you should register an account in the website of [leancloud](https://leancloud.cn/).And follow the steps:

1. In the dashboard, you can create a app with any name you like.
2. Click into the app and click the first icon(like database icon) of menu.
3. Create a class named `blogCounter`(or another name) and choose the last ACL.
4. Now you should go to `setting` and get the `appid`,`app key` in the `application key`
5. Finish your theme config like following config.
6. At last,for your data security,you should set your domain of blog in the `setting > security centre > web-white-list domain`

```yaml
leancloud:
  enable: true
  className: "blogCounter"
  app_id: xxxxx
  app_key: xxxx
  region:
  limits: 10 
```

**Comment by GeekaholicLin** [comment]
Maybe I should turn the default value  of  `enable`  from `true`  to  `false`.

**Comment by EthanLXGu** [comment]
OK. Thanks. I have turn off this function and I will try this one later. Still can not access search function. I will try another way.

**Comment by GeekaholicLin** [comment]
Were there any errors in the console of browser when you turn off the function?Do you configure the `search` in your site config file?
You do not need to install any plugins for the search function because it is built-in.
```yaml
search:
  path: search.xml
  field: all
```

**Comment by GeekaholicLin** [comment]
And you can tell me your blog site,maybe I can find the reason as quickly as possible.

**Comment by EthanLXGu** [comment]
https://ethanlxgu.github.io/ This is my blog. Thank you so much!

**Comment by GeekaholicLin** [comment]
I am so sorry!!!There is a bug of my search function.If the categories or the tags of posts is null,it will be filtered and would  search nothing.And I will try my best to fix it.So sorry!!!

**Comment by GeekaholicLin** [comment]
Maybe it was fixed.You can have a try.You can copy and save your theme config file and download the theme again.If you don't want to download the theme again,[you can just change `search.js` file in `js` folder](https://github.com/GeekaholicLin/hexo-theme-ylion/commit/a8b5254ea631707f94deb059bc3e0c9c09f5ed9d).


Uh...By the way,could you read and understand the `README.md` file?It is hard for me to translate into English(cause my poor English...).If you have any questions about using the theme,you can ask me.:blush:

**Comment by EthanLXGu** [comment]
哈哈 我们可以中文交流～～我去看一下先 太感谢啦！

**Comment by GeekaholicLin** [comment]
:joy: OK
