### ISSUE TITLE
看不到文章縮圖了，全部變成預設圖片

### ISSUE THREAD

**Issue by mosdeo** [GeekaholicLin/hexo-theme-ylion#29]
原本都正常。
我剛剛重新拉 repo 以後，就看不到文章縮圖了，全部變成預設圖片。
但新舊 repo 最後一個 commit 都相同，應該是我原本的手動修改被蓋掉了。

這是我的 _config.yml，看不出哪裡有問題？  
https://gist.github.com/mosdeo/eca0c2fc5587ee6d67649ae6d560b559.js

**Comment by GeekaholicLin** [comment]
格式是这样：

``` yaml
defaultImgs:
  - http://XXXX.example.jpg
  - /img/default-1.jpg
```

注意前面的空格。

**Comment by mosdeo** [comment]
不是這個影響，原本就有空格，剛再加上去也不行。懷疑是 pandoc 造成的差異。
發現如果我文內圖片沒有中文檔名，就可以成為預覽圖，有中文不行。

**Comment by GeekaholicLin** [comment]
不是pandoc的影响，因为我也是用这个渲染引擎。而显示哪一个是主题控制的。（我在主题里面进行了逻辑判断）

你可以`hexo clean`之后再重新生成试试

**Comment by mosdeo** [comment]
其實我都是用
`
hexo clean && hexo g && hexo s
`
---
這是我的文章 source
https://github.com/mosdeo/Stories/tree/master/_posts

只有[這一篇](https://github.com/mosdeo/Stories/blob/master/_posts/%E4%B8%8D%E8%A6%81%E7%9C%8Bnobuy01%E7%9A%84%E7%90%86%E7%94%B1.md)可以正常顯示縮圖，其他都會變成預設圖。

**Comment by GeekaholicLin** [comment]
待我回去先。

**Comment by GeekaholicLin** [comment]
@mosdeo 已经更新主题，你可以备份好配置并重新pull进行更新。我在本地是测试没有问题，但很难保证你的可以通过。

**Comment by mosdeo** [comment]
更新完畢，的確已經改善，感謝大大！
