### ISSUE TITLE
hexo s -g + 访问http://localhost:4000时出现错误

### ISSUE THREAD

**Issue by ShallWe2000** [GeekaholicLin/hexo-theme-ylion#3]
![image](https://cloud.githubusercontent.com/assets/18132309/23837733/ea1ef06c-07c7-11e7-887e-c9ae9eeab8db.png)

我按照安装指南进行了操作，在访问localhost:4000的时候，命令行中显示上图的错误，恳请作者指导一下。

**Comment by GeekaholicLin** [comment]
还请你动手试试，因为我这边无法重现你的错误，初步来看估计是`helper`的正则构建出现了问题。
你可以将[这一行代码](https://github.com/GeekaholicLin/hexo-theme-ylion/blob/master/scripts/helper/pickImgs.js#L3)修改为`var imgRe = /<img.*?\ssrc=[\'\"]\S+[\'\"]\s.*?>/gim`看看是否能解决你的问题

**Comment by ShallWe2000** [comment]
哦， 谢谢， 我重新clone了主题， 问题解决了。
