### ISSUE TITLE
HTML img render 不出來

### ISSUE THREAD

**Issue by mosdeo** [GeekaholicLin/hexo-theme-ylion#30]
[source](https://github.com/mosdeo/Stories/blob/master/_posts/%E8%87%BA%E7%81%A3%E7%81%AB%E7%81%BD%E4%BA%8B%E4%BB%B6%E8%B3%87%E6%96%99%E5%88%86%E6%9E%90(%E4%B8%80).md)

[post](https://mosdeo.github.io/2017/08/22/%E8%87%BA%E7%81%A3%E7%81%AB%E7%81%BD%E4%BA%8B%E4%BB%B6%E8%B3%87%E6%96%99%E5%88%86%E6%9E%90(%E4%B8%80)/)

screen shot  
![2017-08-30 02-57-50](https://user-images.githubusercontent.com/6894543/29838884-191b7f46-8cc2-11e7-870c-7c785ce56bb5.png)

**Comment by GeekaholicLin** [comment]
试着给src属性的值加上双引号。

> <img src=/content/images/2017逢甲火災.JPG width=40% />
改为：
> <img src="/content/images/2017逢甲火災.JPG" width=40% />

**Comment by mosdeo** [comment]
還是一樣。

**Comment by GeekaholicLin** [comment]
嗯。。我刚刚试了一下，确实是一样。还有一处原因，估计是pandoc将你的`img`看成代码块了。因为你缩进了4个空格（或者1个tab），你不需要`p`，直接写`img`就可以了，或者缩进两个空格应该也可以。

但最好是直接写`img`（没有空格），因为`p`标签在这里并没有太大用处

**Comment by mosdeo** [comment]
阿？！我以為代码块不是都要用 ```這種``` 包起來嗎？
總之還是照你的方法搞定了，感謝～

**Comment by GeekaholicLin** [comment]
可以看看pandoc的语法，不过常用的还是三个反引号，比较方便和直观。
