### ISSUE TITLE
关于主题的gitment评论系统初始化多次问题

### ISSUE THREAD

**Issue by GeekaholicLin** [GeekaholicLin/hexo-theme-ylion#31]
@mosdeo 请移步到这里。我们就不要在人家的repo下打扰其他人 😄 

ylion主题已经是集成了`window.location.pathname`，无需另外配置，我看你的配置是正确。
不知你是如何操作的。

**Comment by GeekaholicLin** [comment]
@mosdeo 不知道是否解决了问题？还是说仍然有这个问题？

**Comment by mosdeo** [comment]
剛剛試一下，還是會有重複初始化問題，只要重新整理就會。

**Comment by GeekaholicLin** [comment]
重新整理是什么意思？你不能关闭相关的issue，我看到你关闭了好多。

**Comment by mosdeo** [comment]
阿阿阿原來是不能 closed 啊~
因為 open issue 看了就好煩~
我等等來試看看

**Comment by GeekaholicLin** [comment]
确实有点烦。而且label是根据自己的id生成，一般是路径名，所以label会超级长，看起来并不美观。
