### ISSUE TITLE
LeanCloud 文章瀏覽計數到1就停了

### ISSUE THREAD

**Issue by mosdeo** [GeekaholicLin/hexo-theme-ylion#32]
https://mosdeo.github.io/

剛貼上去是0，自己看了一次是1，但是後來別人看了也不會增加。
排行榜上一個人數到2的，那是我自己從後台修改結果。

後台看都有會有對應紀錄，只是人數到1就不在增加。

**Comment by GeekaholicLin** [comment]
console报错，没有权限(403)

你的后台设置的安全网址是否正确？还是说你设置的时候权限没有打开？

你新建`BlogCounter`的时候需要选择`无限制`选项，这样你才有回写的权限，否则你只有读取阅读人数的权限。而至于安全控制，需要到`设置`添加`Web安全域名`，把你当前的域名添加进去。

> http://blog.geekaholic.cn/2017/03/06/%E5%88%B6%E4%BD%9CHexo%E4%B8%BB%E9%A2%98%E8%AF%A6%E7%BB%86%E6%95%99%E7%A8%8B%EF%BC%882%EF%BC%89/#创建class

**Comment by GeekaholicLin** [comment]
如果你一开始忘记选择了"无限制"，印象中是无法再修改了的。你可以删除`BlogCounter`再重新创建一个Class

**Comment by mosdeo** [comment]
感謝，已解決～
