### ISSUE TITLE
请问评论框怎么设置呢？

### ISSUE THREAD

**Issue by lceCandy** [GeekaholicLin/hexo-theme-ylion#36]
![qq 20170914142905](https://user-images.githubusercontent.com/26810649/30415105-17c51f5a-9959-11e7-99c5-2799176914a9.png)

**Comment by GeekaholicLin** [comment]
`client_id`和`client_secret`的获取和相关配置可以看gitment的使用

> 传送门：https://github.com/imsun/gitment

**Comment by lceCandy** [comment]
弄了一下 提示 初始化 Validation Failed  谢谢你啦 准备用下其他评论系统
