### ISSUE TITLE
iframe 沒辦法置中

### ISSUE THREAD

**Issue by mosdeo** [GeekaholicLin/hexo-theme-ylion#38]
在你這個主題裏面，圖片不論是用 markdown 或是 "<img>" 都可以自動置中。我希望放影片也可以置中，但是 iframe 沒辦法置中，我自己加上 align="middle" 這個屬性設定也不行。

如[這篇文章](https://mosdeo.github.io/2017/10/02/%E6%AD%A5%E4%B8%8A%E8%B3%87%E6%96%99%E7%A7%91%E5%AD%B8%E7%9A%84%E5%BF%83%E8%B7%AF%E6%AD%B7%E7%A8%8B(%E4%B8%80)/)

[原檔案](https://github.com/mosdeo/Stories/blob/master/_posts/%E6%AD%A5%E4%B8%8A%E8%B3%87%E6%96%99%E7%A7%91%E5%AD%B8%E7%9A%84%E5%BF%83%E8%B7%AF%E6%AD%B7%E7%A8%8B(%E4%B8%80).md)

**Comment by GeekaholicLin** [comment]
已经修复。

**Comment by mosdeo** [comment]
已經更新看到修復結果，thanks~
