### ISSUE TITLE
改进：游览器缩小后，最左边的小工具隐藏掉了，看不见了，只有最大化才可以看见

### ISSUE THREAD

**Issue by wubucheng** [GeekaholicLin/hexo-theme-ylion#4]

**Comment by GeekaholicLin** [comment]
当初为了简单地自适应，而且考虑到很少有人用手机或者平板阅读技术文章的时候还用到小组件，当浏览器窗口小于一定的值(980px)的时候就直接隐藏掉了。不知道你有什么好的建议呢？放在下面？

**Comment by GeekaholicLin** [comment]
@wubucheng 已经提供支持，请在窄屏下到[我的博客首页](http://blog.geekaholic.cn/)查看效果。

具体的操作如下：

1. 窄屏查看
2. 点击工具栏（返回顶部等）中的交换按钮即可切换出widgets视图。

欢迎pull下最新的主题代码进行体验~也欢迎后续反馈相关的问题。
