### ISSUE TITLE
文章发表的时间显示的不对，总是显示的上午时间

### ISSUE THREAD

**Issue by vip16** [GeekaholicLin/hexo-theme-ylion#43]
比如是19点45分发表的，实际显示的是07点45

**Comment by vip16** [comment]
我markdown文件里没设置date属性

**Comment by vip16** [comment]
@GeekaholicLin 我markdown文件里没设置date属性

**Comment by GeekaholicLin** [comment]
这就很难受了。你有没有线上文章的地址以及源文件？话说'hexo new post postname'的时候不是会自动添加日期的吗？难道现在改了？

**Comment by Lemonreds** [comment]
dateformat : "HH:mm:ss" 这样小时就会变成24小时的吧！ @vip16 @GeekaholicLin

**Comment by vip16** [comment]
@Lemonreds dateformat是这样的

**Comment by Lemonreds** [comment]
HH是大写的哦！ 确认一样吗

**Comment by vip16** [comment]
@Lemonreds 非常确认

**Comment by vip16** [comment]
@GeekaholicLin 是自动添加日期的，添加的是24小时的，但是在页面上显示就变成了12小时的

**Comment by GeekaholicLin** [comment]
@vip16 不好意思，这阵子因为有一些事在忙，不能及时回复感到抱歉。可不可提供一下你的_comfig.yml以及显示出错的一篇文章的源文件呢？这样子我也不知道问题出现在哪里。主题的渲染只是从Hexo中读取相应的值，还有一种可能就是，用了am和pm的显示，但是我没有获取。所以，能提供一下相关文件是醉吼的了。

**Comment by vip16** [comment]
[_config.txt](https://github.com/GeekaholicLin/hexo-theme-ylion/files/1456931/_config.txt)

**Comment by vip16** [comment]
[_config.txt](https://github.com/GeekaholicLin/hexo-theme-ylion/files/1456940/_config.txt)

**Comment by vip16** [comment]
[markdown.txt](https://github.com/GeekaholicLin/hexo-theme-ylion/files/1456945/markdown.txt)

**Comment by vip16** [comment]
![20171109165141](https://user-images.githubusercontent.com/9410956/32596468-5594e540-c56e-11e7-9906-1c0a68e4597d.jpg)

**Comment by GeekaholicLin** [comment]
啊，说的不清除，不是主题的config，是网站的config，把你个人的敏感信息去掉。

**Comment by GeekaholicLin** [comment]
我大概知道什么原因了。。。主题的锅。

**Comment by GeekaholicLin** [comment]
@vip16 感谢反馈~该bug已修复，原因是主题使用helper函数的时候`HH:mm:ss`写成了`hh:mm:ss`
请拉取最新的主题，注意备份好配置文件，如果重新部署没有问题后，就可以close issue了，再次感谢~

**Comment by vip16** [comment]
@GeekaholicLin 看样子应该是这里了，我呆会试试看。

**Comment by vip16** [comment]
@GeekaholicLin OK，解决了，真棒
