### ISSUE TITLE
文章不支持<!--more-->吗...

### ISSUE THREAD

**Issue by wxlost** [GeekaholicLin/hexo-theme-ylion#48]
文章用了`<!--more-->`在首页还是一堆代码....看起来很乱....
![w9 g4xp0s ov f 04 _9](https://user-images.githubusercontent.com/19698455/37499104-033860ea-28fd-11e8-86a7-86504264b036.png)

想让他呈现这样的效果比较清爽...

![q 94a6r5 4pjty 8kto8 3o](https://user-images.githubusercontent.com/19698455/37499124-1907681c-28fd-11e8-8dc9-6182a3f7709a.png)

**Comment by GeekaholicLin** [comment]
不好意思，暂时不支持。。

**Comment by wxlost** [comment]
暂时嘛?好的
