### ISSUE TITLE
Markdown文档格式

### ISSUE THREAD

**Issue by yeechongyeung** [GeekaholicLin/hexo-theme-ylion#6]
博主把文档格式也上传一份吧，方便应用。谢谢！
比如首页标题处的预览图片链接如何添加标签问题等。
`<div class="article-img img-ajax" data-src= http://7xobsp.com1.z0.glb.clouddn.com/346.jpg>`

或者可以把却省的图片缩略图为一个固定链接（有实际地址），这样就避免了没有指定链接时，图片位置一直加载问题。

**Comment by GeekaholicLin** [comment]
你问的是首页预览图片？我在文档中有说明的哦，可能比较隐蔽吧~我的锅。
``` yaml
### 规则:Front-matter中的自定义'img'字段 > 文章内的图片(随机获取) > defaultImgs(随机获取)
defaultImgs:
  - http://XXXX.example.jpg
  - /img/default-1.jpg
```

也就是说，如果你想指定一个图片，而不是在文章中随机的话，可以在你的文章markdown文件中的font-matter加入img字段。举个栗子：

``` markdown 

title: mathjax
date: 2017-02-19 14:51:32
img: http://XXXX.example.jpg
mathjax: true
categories: [编程之外, hexo]
tags: [Hexo主题, ylion, Mathjax]
top: 9999
---

```

至于你说的这种情况：

> 或者可以把却省的图片缩略图为一个固定链接（有实际地址），这样就避免了没有指定链接时，图片位置一直加载问题。

你可以在配置文件的`defaultImgs`处添加，这样就保证了即使文章没有图片，也忘记在文件中添加`img`字段的时候有一个最后的选择。
