### ISSUE TITLE
代码行号显示问题

### ISSUE THREAD

**Issue by Pipapa** [GeekaholicLin/hexo-theme-ylion#7]
不知道是不是当有两个代码块以上会出现的情况
![](http://og22ev0dc.bkt.clouddn.com/2017-06-17-222307_622x456_scrot.png)

**Comment by GeekaholicLin** [comment]
虽然解决了代码块的问题，但是如果当行代码过长，仍然会出现错乱。见 #9 ，所以当行代码不是很长，可以考虑打开行号显示，否则个人还是建议关闭行号显示，对代码的阅读并无多大影响

**Comment by JERE-MIAH** [comment]
我也是

**Comment by GeekaholicLin** [comment]
@JERE-MIAH 拉取了最新的代码？见 #9 是否是你需要的？
